### ISSUE TITLE
Do you have the implementation for your Structured version of GRasP that was mentioned in the paper?

### ISSUE THREAD

**Issue by johnrachwan123** [StijnVerdenius/SNIP-it#4]

**Comment by StijnVerdenius** [comment]
Hi,
As mentioned in the appendix, structured GraSP didn't work very well. Unfortunately, I don't have the code for that anymore because of that reason.
However, you can reproduce it, by doing the same as SNAP, yet instead using the second-order GraSP saliency scores for the gates instead of the first order ones used in SNAP. Both SNAP and GraSP can be found in the `/models/criterions` subfolder
